spring:
  application:
    name: api-gateway
  sleuth:
    sampler:
      percentage: 1
  zipkin:
    base-url: http://192.168.0.227:9411

server:
  port: 10002
eureka:
  instance:
    hostname: localhost
  client:
#    enabled: true
    register-with-eureka: false
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:${server.port}/eureka/

zuul:
  prefix: /gateway #为zuul设置一个公共的前缀
  #ignoredServices: '*'
  routes:
    eureka-client: #随便定义，当不存在serviceId时，默认该值为serviceId（就是注册服务的名称，属性spring.application.name）
      path: /client/** #匹配/techouse/usersystem/** 均路由到cloud-client
      serviceId: eureka-client #指定路由到的serviceId
#  ribbonIsolationStrategy: THREAD

hystrix:
  command:
    default:
      execution:
        isolation:
          strategy: THREAD

logging:
  level:
    root: INFO
