spring:
  application:
    name: api-gateway
server:
  port: 10301
eureka:
  client:
#    enabled: true
#    register-with-eureka: false
#    fetch-registry: false
    serviceUrl:
      defaultZone: http://localhost:10001/eureka/

zuul:
  prefix: /gateway #为zuul设置一个公共的前缀
  #ignoredServices: '*'
  routes:
    eureka-client: #随便定义，当不存在serviceId时，默认该值为serviceId（就是注册服务的名称，属性spring.application.name）
      path: /client/** #匹配/techouse/usersystem/** 均路由到cloud-client
      serviceId: eureka-client #指定路由到的serviceId