spring:
  application:
    name: eureka-client2
  sleuth:
    sampler:
      percentage: 1
  zipkin:
    base-url: http://192.168.0.227:9411
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
server:
  port: 10102
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    region: double
    availabilityZones:
      double: defaultZone,serverZone
    serviceUrl:
      defaultZone: http://localhost:10002/eureka/
      serverZone: http://localhost:10001/eureka/
feign:
  hystrix:
    enabled: true
  httpclient:
    enabled: false
  okhttp:
    enabled: true
hystrix:
  command:
    default:
      execution:
        isolation:
          strategy: THREAD
          thread:
            timeoutInMilliseconds: 5000
graybunny:
  instance:
    grayEnroll: true #是否在启动后自动注册成灰度实例
  serverUrl: http://localhost:10202 #灰度服务端的url

logging:
  level:
    root: INFO