spring:
  application:
    name: eureka-client
  sleuth:
    sampler:
      percentage: 1
  zipkin:
    base-url: http://192.168.0.227:9411
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
server:
  port: 10101
eureka:
  client:
#    enabled: true
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
#      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
      defaultZone: http://localhost:10002/eureka/,http:localhost:10003/eureka
  instance:
    instanceId: ${spring.application.name}:${server.port}
    metadata-map:
      versions: 1,2

graybunny:
  instance:
    grayEnroll: false
#  serverUrl: http://192.168.6.22:10202